name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # This will run on pushes to the 'main' branch.

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code to the runner

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the version of Python to use

      - name: Install dependencies
        run: |
          pip install --upgrade pip  # Upgrade pip
          pip install flake8  # Install flake8 for code quality checks

      - name: Run flake8
        run: |
          flake8 main.py  # Run flake8 on your main.py file to check code quality

  delivery:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    needs: test  # This ensures that the 'delivery' job only runs after 'test' job completes successfully

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code to the runner

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2  # Set up Docker Buildx for advanced build features

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Set the username from GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Set the password from GitHub Secrets

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .  # Build the Docker image

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest  # Push the image to Docker Hub
